version: '3.9'

services:
  db:
    image: postgres:16.1
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql@16/data/      
      - ./db-postgres/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - default      

  pgadmin:
    image: dpage/pgadmin4:6.13  
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${PGADMIN_LOCAL_PORT:-5050}:${PGADMIN_DOCKER_PORT:-80}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-postgres@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-postgres}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT=False
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED=False      
    volumes:
      - ./db-pgadmin/servers.json:/pgadmin4/servers.json
      - ./db-pgadmin/pgpass:/pgadmin4/pgpass:rw 
      - ./db-pgadmin/pgpass:/var/lib/pgadmin/storage/postgres_example.com/pgpass:rw       
    profiles: ["all"]
    networks:
      - default    

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${CLIENT_LOCAL_PORT:-3000}:${CLIENT_DOCKER_PORT:-3000}
    stdin_open: true
    tty: true
    volumes:
      - ./client-nextjs:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default

  api:
    build:
      context: ./api-nestjs
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${API_LOCAL_PORT:-3001}:${API_DOCKER_PORT:-3001}
    environment:
      - DB_HOST=${POSTGRES_HOST:-host.docker.internal}
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_DATABASE=${POSTGRES_DB:-postgres}
      - DB_PORT=${POSTGRES_PORT:-5432}
    stdin_open: true
    tty: true
    volumes:
      - ./api-nestjs:/app
      - /app/node_modules
    networks:
      - default    

  nxginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./nginx"
    ports:
      - ${NGINX_LOCAL_PORT:-3050}:${NGINX_DOCKER_PORT:-80}

volumes:
  pg_data: