FROM node:20-alpine

WORKDIR /app


# COPY package*.json .
COPY package.json .

RUN npm install
# RUN npm install -g nx@latest

# COPY . .

# CMD start:client:dev:docker:serve

# CMD npm run start:api:dev:docker


# CMD ["node", "dist/apps/api/main.js"] 